import "./globals.css";
import { Assistant } from "next/font/google";
import Providers from "./providers"; // 👈 naya providers file
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const assistantFont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${assistantFont.className} antialiased`}>
        <Providers>
          <ToastContainer />
          {children}
        </Providers>
      </body>
    </html>
  );
}


// import GlobalProvider from "@/components/Application/GlobalProvider";
// import "./globals.css";
// import { Assistant } from 'next/font/google'
// import { ToastContainer, toast } from 'react-toastify';
// import 'react-toastify/dist/ReactToastify.css';
// import Providers from "./providers"; // 👈 sahi import


// const assistantFont = Assistant ({
//   weight: ['400', '500', '600', '700', '800'],
//   subsets: ['latin'],
//   display: 'swap'
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${assistantFont.className} antialiased`}
//       >
//         <GlobalProvider>
//           < ToastContainer/>
//           {children}
//         </GlobalProvider>
        
//       </body>
//     </html>
//   );
// }
